### ISSUE TITLE
Wiki - Exercise 1: Creating a new module

### ISSUE THREAD

**Issue by ajsmith27** [Sitecore/Sitecore.Demo.Group#12]
Is there an issue with the documented NuGet package version of the Sitecore.Kernel package in step 7.iv.?

I'm following along and have been able to find v3.0.0 of the Sitecore.Mvc package but the only version I can find of Sitecore.Kernel is 12.0.0.

Sorry if I'm missing something really obvious!

**Comment by jflheureux** [comment]
You are probably right. Sitecore changed DLL and NuGet packages version numbers twice in the last months to go to semver and back to Sitecore release versions. This documentation was probably written before those changes.
