### ISSUE TITLE
Upgrade to Sitecore 8.2 Update 5

### ISSUE THREAD

**Issue by jbreuer** [Sitecore/Sitecore.Demo.Group#8]
I've installed Habitat with the getting started docs: https://github.com/Sitecore/Habitat/wiki/01-Getting-Started

It says Habitat requires Sitecore Experience Platform 8.2 Update 5.

After adding Sitecore.Demo.Group and running default task (which also publishes) I got an error about "Sitecore.Configuration.Settings.DefaultFontUrl". 

This happend because Sitecore.Demo.Group still runs on Sitecore Experience Platform 8.2 Update 4. After upgrading the NuGet references from 8.2.170614 to 8.2.170728 and doing another publish the error was gone.

**Comment by jbreuer** [comment]
In https://github.com/Sitecore/Sitecore.Demo.Group/wiki/Exercise-1:-Creating-a-new-module 7. Add Sitecore Kernel NuGet reference it says version 8.2.170614 should be installed. This should be 8.2.170728.

**Comment by derekcorreia** [comment]
Agreed -- this solution needs to be updated. I'll take that one.

**Comment by jbreuer** [comment]
Thanks for fixing this. Could you also update the wiki? It still says 8.2.170614 here at 7. iv. and 7. v. https://github.com/Sitecore/Sitecore.Demo.Group/wiki/Exercise-1:-Creating-a-new-module

**Comment by derekcorreia** [comment]
Yes, thanks for pointing that out.
